#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    obj = bld(
        features = 'cxx cstaticlib',
        source   = 'main.cc file.cc testutils.cc',
        uselib   = 'gtests',
        target   = 'unittestmain',
        export_incdirs = '.')

#    bld.add_subdirs('test0')
