######################################################################
# Automatically generated by qmake (2.01a) ? 2? 22 23:11:00 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../cpp

# Input
HEADERS += button.h mainwindow.h select.h ../cpp/Map.h
FORMS += button.ui
SOURCES += main.cc mainwindow.cc select.cc ../cpp/Map.cc
