#!/usr/bin/env python
# encoding: utf-8
# tests/test0

bld(
    features = 'cxx cprogram test',
    source   = 'matrix_loading_test.cc',
    target   = 'unit_test_matrix_loading',
    uselib   = 'gtest',
    uselib_local = 'unittestmain gll',
)
