#!/usr/bin/env python
# encoding: utf-8

bld(
    features = 'cxx cshlib',
    source   = ['gll.cc',
                'similar.cc',
                'sparsify.cc',
                'infer.cc',
                'infer_impl.cc',
                'infer_labelpropagation_impl.cc',
                'infer_localglobal_impl.cc'],
    target   = 'gll',
    includes = '..',
    vnum = '1.0',
    export_incdirs = '.',
)

bld(
    features = 'cxx cprogram',
    source   = 'main.cc',
    target   = 'gll_induction',
    includes = '..',
    uselib_local = 'gll',
)

## tests

tests = ['gll_unittest.cc',
         'similar_unittest.cc',
         'sparsify_unittest.cc',
         'infer_localglobal_impl_unittest.cc',
         'infer_impl_unittest.cc',
         ]

for unit in tests:
    bld(
        features = 'cxx cprogram gtest',
        source   = [unit, '../testing/utils.cc'],
        target   = unit[:-3],
        uselib_local = 'gll',
        includes = '..',
    )
